spring:
  application:
    name: api
  datasource:
    url: jdbc:mariadb://localhost:3306/api_spring
    username: root
    password: 91344356
    driver-class-name: org.mariadb.jdbc.Driver
#    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
    token:
      secret: YXJvbWFkb2NvZGlzb3JlY2Vpc2RlYXBpc3ByaW5nYm9vdGNvbWp3dGlzYmVzdGNoYXJzZXQ=
      expiration-time: 3600000
